---
- hosts: localhost
  connection: local
  become: true
  vars:
    users:
      - jmanzur
      - root
  pre_tasks:
  - name: Update and Upgrade
    apt:
      update_cache: yes
      upgrade: 'yes'

  tasks:
  - name: Install packages
    package:
      name:
        - gnupg
        - software-properties-common
        - htop
        - vim
        - curl
        - net-tools
        - sshpass
        - dos2unix
        - telnet
        - whois
        - tree
        - neofetch
        - jq
        - pass
        - gnupg2
        - silversearcher-ag
        - zsh
        - flatpak
        - gnome-software-plugin-flatpak
        - tmux
        - docker
        - docker-compose

  - name: Add jmanzur to the sudoers file
    blockinfile:
      path: /etc/sudoers
      insertafter: 'root  ALL=(ALL:ALL) ALL'
      block: |
        jmanzur  ALL=(ALL:ALL) ALL

  - name: Add user to the Docker group.
    user:
      name: jmanzur
      groups: docker
      append: yes

  - name: Add the Flathub repository
    command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Download Oh My Zsh installation script
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /tmp/install_ohmyzsh.sh

  - name: Run Oh My Zsh installation script
    command: sh /tmp/install_ohmyzsh.sh --unattended
    register: ohmyzsh_result
    failed_when: "'FAILED' in ohmyzsh_result.stderr"

  - name: Remove Firefox ESR
    apt:
      name: firefox-esr
      state: absent
  
  - name: Install standar firefox from flatpak
    flatpak:
      name: org.mozilla.firefox
      state: present

  - name: Install Google Chrome
    flatpak:
      name: com.google.Chrome
      state: present

  - name: Install Visual Studio Code
    flatpak:
      name: com.visualstudio.code
      state: present

  - name: Install Spotify
    flatpak:
      name: com.spotify.Client
      state: present

  - name: Install Slack
    flatpak:
      name: com.slack.Slack
      state: present

  - name: Install Zoom
    flatpak:
      name: us.zoom.Zoom
      state: present

  - name: Install VLC
    flatpak:
      name: org.videolan.VLC
      state: present

  - name: Install OBS Studio
    flatpak:
      name: com.obsproject.Studio
      state: present

  - name: Install Obsidian
    flatpak:
      name: md.obsidian.Obsidian
      state: present

  - name: Install draw.io
    flatpak:
      name: io.drawio.desktop
      state: present