---
- hosts: localhost
  connection: local
  become: true
  vars:
    users:
      - jmanzur
      - root
  pre_tasks:
  - name: Update and Upgrade
    apt:
      update_cache: yes
      upgrade: 'yes'

  tasks:
  - name: Install packages
    package:
      name:
        - gnupg
        - software-properties-common
        - htop
        - vim
        - curl
        - net-tools
        - sshpass
        - dos2unix
        - telnet
        - whois
        - tree
        - neofetch
        - jq
        - pass
        - gnupg2
        - silversearcher-ag
        - zsh
        - flatpak
        - gnome-software-plugin-flatpak
        - tmux

  - name: Add jmanzur to the sudoers file
    blockinfile:
      path: /etc/sudoers
      insertafter: 'root  ALL=(ALL:ALL) ALL'
      block: |
        jmanzur  ALL=(ALL:ALL) ALL

  - name: Add the Flathub repository
    command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Install Oh-My-Zsh
    command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

  - name: Remove Firefox ESR
    apt:
      name: firefox-esr
      state: absent
  
  - name: Install standar firefox from flatpak
    flatpak:
      name: org.mozilla.firefox
      state: present